# Generated by Django 3.0.4 on 2020-03-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NoFirstNane', max_length=50)),
                ('last_name', models.CharField(default='NoLastName', max_length=50)),
                ('description', models.TextField(default='No Description Availiable')),
            ],
        ),
    ]
